name: tesla_inventory_bot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag tesla_inventory_bot:$(date +%s)
      env:
        CR_PAT: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
      - name: Login to GitHub Container Registry
        run: |
        echo $CR_PAT | docker login ghcr.io -u swtpumpkin --password-stdin
      - name: Push on GitHub Container Registry
        run: docker push ghcr.io/swtpumpkin/tesla_inventory_bot:$(date +%s)
